# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OPuSaSW6YCg7nwEsvqitdkSV_B4sIZ7
"""

import pandas as pd

def load_data(path='dataset.csv'):
    try:
        df = pd.read_csv(path)
        print("Dataset loaded successfully.")
        print(df.head())
        return df
    except FileNotFoundError:
        print("Dataset file not found.")
        return None

if _name_ == "_main_":
    load_data()